Repository gisaia/ARLAS-web-contributors, pull requests merged in 2019-01, with the labels that each got.

#129 Fix mkDoc image version
  mkDocs.sh
Labels: type:bug

#131 Implement update powerbars data
  package-lock.json
  package.json
  src/contributors/PowerbarsContributor.ts
Labels: type:enhancement

#132 Fix package release core version
  package-release.json
Labels: type:maintenance

#133 Fix search value powerBars
  src/contributors/PowerbarsContributor.ts
Labels: type:bug

#135 Fix the selected nodes list construction
  src/contributors/DonutContributor.ts
Labels: type:bug

#145 Fix json schema import in TreeContributor
  src/contributors/TreeContributor.ts
Labels: type:bug

#146 Fix bug icon title field value missing
  src/contributors/ResultListContributor.ts
  src/jsonSchemas/resultlistContributorConf.schema.json
Labels: type:bug
